[parameters]
ame_file = "mass16.rd"
elbien_file = "ElBiEn_2007.dat"
revtime_file = "revlutiontime_72Ge.txt"
initial_params = "[-0.6880425289251325, 2.9730599061989426e-06, 5.55756235663825e-12]"
p = "2"
iterationMax = "100"
OutputMatrixOrNot = "false"
me_vs_tof_x_min = "500"
me_vs_tof_x_max = "600"
me_vs_tof_y_min = "-150"
me_vs_tof_y_max = "150"
label_offset = "10"
draw_individual_fits = "true"
