[parameters]
ame_file = "/home/chenruijiu-ubuntu/MassCalibration/mass16.rd"
elbien_file = "/home/chenruijiu-ubuntu/MassCalibration/ElBiEn_2007.dat"
revtime_file = "/home/chenruijiu-ubuntu/mass_72Ge_exp/revlutiontime_72Ge.txt"
initial_params = "[-0.6880425289251325, 2.9730599061989426e-06, 5.55756235663825e-12]"
p = "2"
iterationMax = "200"
OutputMatrixOrNot = "True"
me_vs_tof_x_min = "500"
me_vs_tof_x_max = "600"
me_vs_tof_y_min = "-300"
me_vs_tof_y_max = "300"
label_offset = "10"
draw_individual_fits = "true"
